name: CI

on:
  push:
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: cargo build with all features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get update && sudo apt-get install -y curl build-essential gcc-multilib zlib1g-dev libelf-dev libclang-dev libpcap-dev llvm clang pkg-config
      - run: cargo build --all-features

  test-all-features:
    name: cargo test with all features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get update && sudo apt-get install -y curl build-essential gcc-multilib zlib1g-dev libelf-dev libclang-dev libpcap-dev llvm clang pkg-config
      - run: lscpu
      - run: cargo test
        env:
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER: 'sudo -E'

  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions-rust-lang/audit@v1