name: CI

on:
  push:
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: cargo build with all features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get update && sudo apt-get install -y curl build-essential zlib1g-dev libelf-dev libclang-dev llvm clang pkg-config;
      - run: cargo build --all-features

